#####
# @name userAuth
POST {{baseUrl}}/users/auth HTTP/1.1
Content-Type: application/json

{
	"username2": "user1",
	"password2": "senha@123"
}

#### Variable Response
@accessToken = {{userAuth.response.body.$.token}}

#####
## Create Job
POST {{baseUrl}}/jobs HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
	"title": "Título 004",
	"description": "Descrição 004",
	"company": "Teste DEV",
	"email": "nilson.mello2@live.com",
	"techs": [
		"Java",
		"JPA",
		"Hibernate",
		"Spring Boot",
		"Spring Data JPA",
		"Spring Security"
	],
	"status": "OPEN"
}
